version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"

  app:
    image: myapp:latest
    build:
      context: src/main/java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db